### ISSUE TITLE
Support params attribute

### ISSUE THREAD

**Issue by vzam** [m31coding/M31.FluentAPI#2]
Currently, when using FluentMethod with params, the params attribute is missing in the generated code. For example in `public void UseThis(params string[] items)`, the generated code will only have `string[] items` as the parameter. See also [ParamsArrayAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.paramarrayattribute?view=net-8.0).

**Comment by vzam** [comment]
I think it should be considered to keep all attributes that were defined on the `FluentMethod` and maybe even `FluentMember`, as they could carry useful information. For example there is also the `[StringFormatMethod("message")]` attribute from JetBrains to give hints that a method accepts interpolated strings and enables the appropriate analyzers on the parameters.

**Comment by m31coding** [comment]
Thank you for this! I am going to fix it and test it with `params` as well as with other [parameter modifiers](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/method-parameters#reference-parameters).
