### ISSUE TITLE
Feature: Allow inheritance

### ISSUE THREAD

**Issue by vzam** [m31coding/M31.FluentAPI#29]
I currently have a use case where I created an abstract builder which receives a bunch of type parameters and the idea is that it would be possible to inherit from that builder and specify some of those type parameters. This would allow to have a generic implementation of a builder and a few ones which are very specific to their use case and project:

```csharp
// no FluentApi
public abstract class GenericBuilder<T>
{
  [FluentMember]
  public T Content { get; set; }
}

[FluentApi]
public class ConcreteBuilder : GenericBuilder<int>

var builder = CreateConcreteBuilder.WithContent(1);
```

**Comment by m31coding** [comment]
Thank you for your request! Inheritance is the next feature I would like to look into.

Best regards,
Kevin

**Comment by Sam13** [comment]
Hi @m31coding 

What is the best practice to deal with the situation when the inherited type has less parameters in the constructor and provides some predefined values to the base type?

Simplified example:
```csharp
[FluentApi]
public abstract record Creature(
    [property: FluentMember(0)] string PlanetName,
    [property: FluentMember(1)] string FirstName,
    [property: FluentMember(2)] string LastName);

[FluentApi]
public sealed record Martian(
    string FirstName,
    string LastName)
    : Creature(
        "Mars",
        FirstName,
        LastName);
```

the following doesn't work:
```csharp
CreateMartian
    .WithFirstName("Hans")
    .WithLastName("Martian");
```

In this simple example I could add `FluentSkippable` to the `PlanetName` argument - but this get's kinda complicated if you have lots of such parameters with multiple types inheriting from the same base class.
You might end up adding the skippable attribute to all parameters...

**Comment by m31coding** [comment]
Hi @Sam13,

That is a very good question and I currently don't have a good answer to this use case. Constructors are not taken into account by the Fluent API (they are merely used to instantiate the object with default values). Hence, the gist of the question is 'How to provide predefined values to the base class'? Unfortunately, I assume new syntax / a new feature is required to make this work.

I'll look into this further, and in the meantime, if you have any ideas or suggestions, please let me know!

Best regards,
Kevin
