### ISSUE TITLE
Support default values

### ISSUE THREAD

**Issue by vzam** [m31coding/M31.FluentAPI#3]
Currently, when using `FluentMethod` with default values, the FluentApi does not keep the default values in the generated builder, such that the value always has to be provided. It would be nice if the generator was able to carry them over. See also [ParameterInfo.DefaultValue](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.parameterinfo.defaultvalue?view=net-8.0). It would be interesting if the `FluentMethod` also allowed different signatures for the same method name at the same step, although I can imagine that overloads are supported already (I didn't verify that).

**Comment by m31coding** [comment]
Thank you, good catch! Yes, overloads are already working.
